import axios from 'axios';

const BASE_URL = import.meta.env.VITE_API_URL || '/api';

export const api = axios.create({
  baseURL: BASE_URL,
  timeout: 15000, // 15s: accommodates SDK polling window + server processing time
});

// Fast instance for latency-sensitive auth calls (jt-auth must complete within 8s)
const fastApi = axios.create({
  baseURL: BASE_URL,
  timeout: 8000,
});

// ─── Response interceptor ─────────────────────────────────────────────────────
const responseErrorHandler = (error: any) => {
  if (error.response?.status === 401) {
    console.warn('[API] 401 Unauthorized — initData may be invalid or expired');
  } else if (error.response?.status >= 500) {
    console.error('[API] Server error:', error.response?.status, error.response?.data);
  } else if (!error.response) {
    console.error('[API] Network error — no response received:', error.message);
  }
  return Promise.reject(error);
};

api.interceptors.response.use((response) => response, responseErrorHandler);
fastApi.interceptors.response.use((response) => response, responseErrorHandler);

// ─── Init data management ──────────────────────────────────────────────────────
export function setInitData(initData: string) {
  if (initData) {
    api.defaults.headers.common['X-Telegram-Init-Data'] = initData;
  }
}

// ─── Session token management ─────────────────────────────────────────────────
const SESSION_TOKEN_LS_KEY = 'enkpay_session_token';

/**
 * Persist a session token (issued by /api/miniapp/jt-auth or /api/miniapp/auth-sync) so that
 * all subsequent API requests authenticate via X-Session-Token instead of
 * re-validating initData HMAC on every request.
 * Also writes to localStorage so the token survives page reloads.
 */
export function setSessionToken(sessionToken: string) {
  if (sessionToken) {
    api.defaults.headers.common['X-Session-Token'] = sessionToken;
    fastApi.defaults.headers.common['X-Session-Token'] = sessionToken;
    try { localStorage.setItem(SESSION_TOKEN_LS_KEY, sessionToken); } catch { /* non-critical */ }
  }
}

/** Remove session token from axios headers and localStorage. */
export function clearSessionToken() {
  delete api.defaults.headers.common['X-Session-Token'];
  delete fastApi.defaults.headers.common['X-Session-Token'];
  try { localStorage.removeItem(SESSION_TOKEN_LS_KEY); } catch { /* non-critical */ }
}

/** Return the session token stored in localStorage (null if absent or unavailable). */
export function getStoredSessionToken(): string | null {
  try { return localStorage.getItem(SESSION_TOKEN_LS_KEY); } catch { return null; }
}

// Auto-restore session token from localStorage on module load (survives page reloads).
const _storedToken = getStoredSessionToken();
if (_storedToken) {
  // Use direct header assignment (not setSessionToken) to avoid a redundant localStorage write.
  api.defaults.headers.common['X-Session-Token'] = _storedToken;
  fastApi.defaults.headers.common['X-Session-Token'] = _storedToken;
}

// ─── User Profile ─────────────────────────────────────────────────────────────
export async function getUserProfile() {
  const response = await api.get('/miniapp/profile');
  return response.data;
}

// ─── Auth Sync ────────────────────────────────────────────────────────────────
export async function authSync(initData: string) {
  const response = await api.post('/miniapp/auth-sync', {}, {
    headers: { 'X-Telegram-Init-Data': initData },
  });
  return response.data;
}

// ─── JT Token Auth (Phase 1 — bypasses initData HMAC) ────────────────────────
/**
 * Exchange a one-time ?jt= URL token for a session token + user profile.
 * Called immediately on Mini App mount, before Telegram SDK is ready.
 * The token was generated by the Bot on /start and stored in Redis.
 * Uses an 8s timeout to allow for network latency while still surfacing failures quickly.
 */
export async function jtAuth(jt: string) {
  const response = await fastApi.post('/miniapp/jt-auth', { jt });
  return response.data;
}

// ─── Trading ──────────────────────────────────────────────────────────────────
export async function getTradingPairs() {
  const response = await api.get('/trading/pairs');
  return response.data;
}

export async function getTradingPairPrice(pairId: string) {
  const response = await api.get(`/trading/pairs/${pairId}/price`);
  return response.data;
}

export async function getTradingPairRules(pairId: string, duration?: number) {
  const params = duration ? { duration } : {};
  const response = await api.get(`/trading/pairs/${pairId}/rules`, { params });
  return response.data;
}

export async function placeQuickSession(params: {
  pair_id: string;
  duration: number;
  direction: 'up' | 'down';
  amount: number;
}) {
  const response = await api.post('/trading/quick-session', params);
  return response.data;
}

export async function getMyOrders(options?: { status?: string; limit?: number }) {
  const response = await api.get('/trading/orders/my', {
    params: options,
  });
  return response.data;
}

// ─── Products / NFT ───────────────────────────────────────────────────────────
export async function getProducts() {
  const response = await api.get('/nft/products');
  return response.data;
}

// ─── Charity ─────────────────────────────────────────────────────────────────
export async function getCharityActivities() {
  const response = await api.get('/charity/activities');
  return response.data;
}

// ─── Transactions ─────────────────────────────────────────────────────────────
export async function getTransactions() {
  const response = await api.get('/miniapp/transactions');
  return response.data;
}

// ─── Announcements ────────────────────────────────────────────────────────────
export async function getAnnouncements(showOnLaunch?: boolean) {
  const params = showOnLaunch ? { show_on_app_launch: true } : {};
  const response = await api.get('/miniapp/announcements', { params });
  return response.data;
}

// ─── Language ─────────────────────────────────────────────────────────────────
export async function updateLanguage(langCode: string) {
  const response = await api.post('/miniapp/language', { language_code: langCode });
  return response.data;
}

// ─── Auctions ────────────────────────────────────────────────────────────────
export async function getAuctions(status = 'active') {
  const response = await api.get('/auctions', { params: { status } });
  return response.data;
}

export async function getAuctionDetail(id: string) {
  const response = await api.get(`/auctions/${id}`);
  return response.data;
}

export async function joinAuction(id: string, quantity: number) {
  const response = await api.post(`/auctions/${id}/join`, { quantity });
  return response.data;
}

export async function getAuctionResults() {
  const response = await api.get('/auctions/results');
  return response.data;
}

export async function getMyAuctions() {
  const response = await api.get('/auctions/my');
  return response.data;
}

export async function redeemAuction(resultId: string) {
  const response = await api.post(`/auctions/results/${resultId}/redeem`, {});
  return response.data;
}

// ─── Agreement ────────────────────────────────────────────────────────────────

export async function getAgreement() {
  const response = await api.get('/miniapp/agreement');
  return response.data;
}


// ─── QR Code Payment ──────────────────────────────────────────────────────────

export async function verifyQRCode(content: string) {
  const response = await api.post('/qrcode/verify', { content });
  return response.data;
}

export async function submitTransferWithPassword(params: {
  to_identifier: string;
  amount: number;
  password: string;
}) {
  const response = await api.post('/wallet/transfer', params);
  return response.data;
}
