import crypto from 'crypto';
import express from 'express';
import { query } from '../db';
import { authenticateMiniApp, MiniAppAuthRequest } from '../middleware/miniapp-auth';
import { buildCanonicalProfile, upsertUserFromTelegramId } from './miniapp-shared';
import { getCache, setCache } from '../utils/cache';
import { sessionTokenKey, jtTokenKey } from '../utils/cache-keys';

const router = express.Router();

/**
 * POST /api/miniapp/preregister
 * Called by the Bot on /start to pre-register or refresh user info.
 * Auth: X-Bot-Id header (must match an active bot in the DB).
 * Body: { telegram_id, first_name?, username?, language_code? }
 */
router.post('/preregister', async (req, res) => {
  try {
    const botId = req.headers['x-bot-id'] as string;
    if (!botId) return res.status(403).json({ error: 'Missing X-Bot-Id header' });

    // Verify bot is active
    const botResult = await query(
      `SELECT id FROM bots WHERE id = $1 AND is_active = true LIMIT 1`,
      [botId]
    );
    if (botResult.rows.length === 0) {
      return res.status(403).json({ error: 'Bot not found or inactive' });
    }

    const { telegram_id, first_name, username, language_code } = req.body as {
      telegram_id?: number;
      first_name?: string;
      username?: string;
      language_code?: string;
    };
    if (!telegram_id || typeof telegram_id !== 'number') {
      return res.status(400).json({ error: 'telegram_id (number) is required' });
    }

    await upsertUserFromTelegramId(telegram_id, {
      firstName: first_name,
      username,
      languageCode: language_code,
    });

    return res.json({ success: true });
  } catch (err: any) {
    console.error('[miniapp/preregister] error:', err?.message);
    return res.status(500).json({ error: 'Internal server error' });
  }
});

/**
 * POST /api/miniapp/jt-store
 * Called by the Bot to store a jt token in Redis.
 * Auth: X-Bot-Id header.
 * Body: { jt, telegram_id, bot_id, first_name?, username?, language_code?, ttl? }
 */
router.post('/jt-store', async (req, res) => {
  try {
    const botId = req.headers['x-bot-id'] as string;
    if (!botId) return res.status(403).json({ error: 'Missing X-Bot-Id header' });

    const botResult = await query(
      `SELECT id FROM bots WHERE id = $1 AND is_active = true LIMIT 1`,
      [botId]
    );
    if (botResult.rows.length === 0) {
      return res.status(403).json({ error: 'Bot not found or inactive' });
    }

    const { jt, telegram_id, bot_id, first_name, username, language_code, ttl } = req.body as {
      jt?: string;
      telegram_id?: number;
      bot_id?: string;
      first_name?: string;
      username?: string;
      language_code?: string;
      ttl?: number;
    };

    if (!jt || typeof jt !== 'string' || jt.length !== 64) {
      return res.status(400).json({ error: 'jt must be a 64-char hex string' });
    }
    if (!telegram_id || typeof telegram_id !== 'number') {
      return res.status(400).json({ error: 'telegram_id (number) is required' });
    }

    const tokenTtl = typeof ttl === 'number' && ttl > 0 ? Math.min(ttl, 86400) : 86400;

    await setCache(
      jtTokenKey(jt),
      {
        telegramId: telegram_id,
        botId: bot_id || botId,
        firstName: first_name || '',
        username: username || null,
        languageCode: language_code || 'zh',
      },
      tokenTtl
    );

    return res.json({ success: true });
  } catch (err: any) {
    console.error('[miniapp/jt-store] error:', err?.message);
    return res.status(500).json({ error: 'Internal server error' });
  }
});

/**
 * POST /api/miniapp/jt-auth
 * Exchange a ?jt= URL token (generated by the Bot on /start) for a
 * session token + canonical user profile.
 * No Telegram initData or HMAC required — the token itself is the credential.
 * The token uses a sliding-window TTL: after each successful use the TTL is
 * reset to JT_SLIDING_WINDOW_TTL_SECONDS, allowing Telegram's cached WebApp URL
 * to be reopened within that window without requiring the user to go back to
 * the Bot.
 */
const JT_SLIDING_WINDOW_TTL_SECONDS = 86400; // 24 hours
router.post('/jt-auth', async (req, res) => {
  try {
    const { jt } = req.body as { jt?: string };
    if (!jt || typeof jt !== 'string' || jt.length !== 64) {
      return res.status(400).json({ error: 'jt token is required' });
    }

    const key = jtTokenKey(jt);
    const payload = await getCache<{
      telegramId: number;
      botId: string;
      firstName?: string;
      username?: string;
      languageCode?: string;
    }>(key);

    if (!payload?.telegramId) {
      return res.status(401).json({ error: 'Token invalid or expired', code: 'JT_INVALID' });
    }

    // Sliding-window: reset TTL to JT_SLIDING_WINDOW_TTL_SECONDS instead of deleting immediately.
    // This allows Telegram's cached WebApp URL to be reopened within the window
    // without requiring the user to restart the Bot.
    await setCache(key, payload, JT_SLIDING_WINDOW_TTL_SECONDS);

    const { telegramId, botId, firstName, username, languageCode } = payload;

    // Upsert user with the real info the Bot captured
    await upsertUserFromTelegramId(telegramId, {
      firstName: firstName || '',
      username: username || undefined,
      languageCode: languageCode || 'zh',
    });

    const userProfile = await buildCanonicalProfile(telegramId);
    if (!userProfile) {
      return res.status(404).json({ error: 'User not found after upsert' });
    }

    // Mint a 24-hour session token
    const sessionToken = crypto.randomBytes(32).toString('hex');
    await setCache(
      sessionTokenKey(sessionToken),
      { telegramId, botId },
      86400
    );

    console.info(`[miniapp/jt-auth] Success for telegramId=${telegramId} botId=${botId}`);

    return res.json({
      success: true,
      user: userProfile,
      session_token: sessionToken,
    });
  } catch (err: any) {
    console.error('[miniapp/jt-auth] error:', err?.message);
    return res.status(500).json({ error: 'Internal server error' });
  }
});

/**
 * GET /api/miniapp/profile
 * Get current user's profile (authenticated via Telegram initData)
 */
router.get('/profile', authenticateMiniApp, async (req: MiniAppAuthRequest, res) => {
  try {
    const telegramId = req.telegramUser?.id;
    if (!telegramId) return res.status(401).json({ error: 'Unauthorized' });

    const userProfile = await buildCanonicalProfile(telegramId);
    if (!userProfile) {
      return res.status(404).json({ error: 'User not found' });
    }

    res.json({ success: true, user: userProfile });
  } catch (error: any) {
    console.error('Miniapp profile error:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * GET /api/miniapp/transactions
 * Get current user's transaction history from transfer_records, deposit_records,
 * withdrawal_records, and trading_orders (UNION query).
 */
router.get('/transactions', authenticateMiniApp, async (req: MiniAppAuthRequest, res) => {
  try {
    const telegramId = req.telegramUser?.id;
    if (!telegramId) return res.status(401).json({ error: 'Unauthorized' });

    // Use canonical user id for consistent cross-bot query (ORDER BY + LIMIT 1 prevents
    // returning a random row when legacy duplicate telegram_id records exist)
    const userResult = await query(
      `SELECT id FROM users WHERE telegram_id = $1 ORDER BY created_at ASC LIMIT 1`,
      [telegramId]
    );
    if (userResult.rows.length === 0) return res.status(404).json({ error: 'User not found' });
    const userId = userResult.rows[0].id;

    const parsedLimit = parseInt(String(req.query.limit ?? '50'), 10);
    const limitNum = isNaN(parsedLimit) || parsedLimit <= 0 ? 50 : Math.min(parsedLimit, 200);

    const result = await query(
      `SELECT id, type, amount, status, created_at, description, order_id
       FROM (
         -- Incoming transfers
         SELECT id::text, 'transfer_in' AS type, amount::numeric, status,
                created_at, NULL AS description, order_id
         FROM transfer_records
         WHERE to_user_id = $1

         UNION ALL

         -- Outgoing transfers
         SELECT id::text, 'transfer_out' AS type, amount::numeric, status,
                created_at, NULL AS description, order_id
         FROM transfer_records
         WHERE from_user_id = $1

         UNION ALL

         -- Deposits
         SELECT id::text, 'deposit' AS type, amount::numeric, status,
                created_at, tx_hash AS description, NULL AS order_id
         FROM deposit_records
         WHERE user_id = $1

         UNION ALL

         -- Withdrawals
         SELECT id::text, 'withdrawal' AS type, amount::numeric, status,
                created_at, to_address AS description, order_id
         FROM withdrawal_records
         WHERE user_id = $1

         UNION ALL

         -- Trading orders (instant trades)
         SELECT id::text,
                CASE WHEN profit >= 0 THEN 'trade_win' ELSE 'trade_loss' END AS type,
                CASE WHEN profit >= 0 THEN (amount * odds)::numeric ELSE amount::numeric END AS amount,
                status,
                created_at, pair_id::text AS description, NULL AS order_id
         FROM trading_orders
         WHERE user_id = $1

         UNION ALL

         -- Other transaction types from ledger (product, auction, rewards, etc.)
         -- Excludes types already fetched from their dedicated tables above:
         --   transfer_in/out → transfer_records
         --   deposit         → deposit_records
         --   withdrawal      → withdrawal_records
         --   trade_win/loss  → trading_orders
         SELECT id::text,
                type,
                ABS(amount)::numeric,
                'completed' AS status,
                created_at,
                description,
                reference_id::text AS order_id
         FROM transactions
         WHERE user_id = $1
           AND type NOT IN (
             'transfer_in','transfer_out','deposit','withdrawal','trade_win','trade_loss'
           )
       ) AS combined
       ORDER BY created_at DESC
       LIMIT $2`,
      [userId, limitNum]
    );

    res.json({ success: true, transactions: result.rows });
  } catch (error: any) {
    console.error('Miniapp transactions error:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * GET /api/miniapp/announcements
 * Get public announcements (optionally filtered by show_on_app_launch)
 */
router.get('/announcements', async (req, res) => {
  try {
    const { show_on_app_launch } = req.query;

    let queryText = `SELECT id, title, content, images, is_pinned, show_on_app_launch,
                            content_translations, title_translations, created_at
                     FROM announcements WHERE status = 'sent' AND targets @> '["app"]'`;
    const params: any[] = [];

    if (show_on_app_launch === 'true') {
      queryText += ` AND show_on_app_launch = true`;
    }

    queryText += ` ORDER BY is_pinned DESC, created_at DESC LIMIT 20`;

    const result = await query(queryText, params);
    res.json({ success: true, announcements: result.rows });
  } catch (error: any) {
    console.error('Miniapp announcements error:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * Resolve the canonical user ID for a given Telegram ID.
 * ORDER BY created_at ASC LIMIT 1 ensures the earliest (canonical) record is returned
 * even if legacy duplicate telegram_id rows exist before migration 020 was applied.
 */
async function getCanonicalUserId(telegramId: number): Promise<string | null> {
  const result = await query(
    `SELECT id FROM users WHERE telegram_id = $1 ORDER BY created_at ASC LIMIT 1`,
    [telegramId]
  );
  if (result.rows.length === 0) return null;
  return result.rows[0].id;
}

/**
 * POST /api/miniapp/language
 * Update user's language preference (targets canonical record)
 */
router.post('/language', authenticateMiniApp, async (req: MiniAppAuthRequest, res) => {
  try {
    const telegramId = req.telegramUser?.id;
    if (!telegramId) return res.status(401).json({ error: 'Unauthorized' });
    const { language_code, language } = req.body;
    const lang = language_code || language;
    if (!lang) return res.status(400).json({ error: 'language_code is required' });

    const canonicalId = await getCanonicalUserId(telegramId);
    if (!canonicalId) return res.status(404).json({ error: 'User not found' });

    await query(
      `UPDATE users SET language_code = $1 WHERE id = $2`,
      [lang, canonicalId]
    );

    res.json({ success: true });
  } catch (error: any) {
    console.error('Miniapp language error:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * PUT /api/miniapp/language
 * Update user's language preference (alias for POST, supports both methods)
 */
router.put('/language', authenticateMiniApp, async (req: MiniAppAuthRequest, res) => {
  try {
    const telegramId = req.telegramUser?.id;
    if (!telegramId) return res.status(401).json({ error: 'Unauthorized' });
    const { language_code, language } = req.body;
    const lang = language_code || language;
    if (!lang) return res.status(400).json({ error: 'language_code is required' });

    const canonicalId = await getCanonicalUserId(telegramId);
    if (!canonicalId) return res.status(404).json({ error: 'User not found' });

    await query(
      `UPDATE users SET language_code = $1 WHERE id = $2`,
      [lang, canonicalId]
    );

    res.json({ success: true });
  } catch (error: any) {
    console.error('Miniapp language PUT error:', error);
    res.status(500).json({ error: error.message });
  }
});

/**
 * POST /api/miniapp/sync-user
 * Sync Telegram user info (first_name, username, language_code) to the canonical DB record.
 * Targets the earliest-created user record to stay consistent with /profile reads.
 */
router.post('/sync-user', authenticateMiniApp, async (req: MiniAppAuthRequest, res) => {
  try {
    const telegramId = req.telegramUser?.id;
    if (!telegramId) return res.status(401).json({ error: 'Unauthorized' });

    const { first_name, username, language_code } = req.body;

    const canonicalId = await getCanonicalUserId(telegramId);
    if (!canonicalId) return res.status(404).json({ error: 'User not found' });

    const updates: string[] = [];
    const values: any[] = [];
    let idx = 1;

    if (first_name !== undefined) { updates.push(`first_name = $${idx++}`); values.push(first_name); }
    if (username !== undefined) { updates.push(`username = $${idx++}`); values.push(username); }
    if (language_code !== undefined) { updates.push(`language_code = $${idx++}`); values.push(language_code); }

    if (updates.length > 0) {
      values.push(canonicalId);
      await query(
        `UPDATE users SET ${updates.join(', ')} WHERE id = $${idx}`,
        values
      );
    }

    res.json({ success: true });
  } catch (error: any) {
    console.error('Miniapp sync-user error:', error);
    res.status(500).json({ error: error.message });
  }
});

// buildCanonicalProfile is now exported from ./miniapp-shared and imported above.

/**
 * POST /api/miniapp/auth-sync
 * One-shot: validate Telegram initData, atomically upsert the user record, and
 * return the canonical profile.
 * Delegates to upsertUserFromTelegramId which uses INSERT … ON CONFLICT (telegram_id)
 * DO UPDATE — race-free and consistent with the UNIQUE constraint from migration 020/021.
 */
router.post('/auth-sync', authenticateMiniApp, async (req: MiniAppAuthRequest, res) => {
  try {
    const tgUser = req.telegramUser;
    if (!tgUser?.id) return res.status(401).json({ error: 'Unauthorized' });

    await upsertUserFromTelegramId(tgUser.id, {
      firstName: tgUser.first_name || '',
      username: tgUser.username || undefined,
      languageCode: tgUser.language_code || 'zh',
    });

    const userProfile = await buildCanonicalProfile(tgUser.id);
    if (!userProfile) {
      return res.status(404).json({ error: 'User not found after upsert' });
    }

    // Mint a 24-hour session token (mirrors jt-auth so Phase 0 works on next load)
    const sessionToken = crypto.randomBytes(32).toString('hex');
    await setCache(
      sessionTokenKey(sessionToken),
      // botId is empty for initData-based auth (no single bot context; telegramId is the identity)
      { telegramId: tgUser.id, botId: '' },
      86400
    );

    res.json({ success: true, user: userProfile, session_token: sessionToken });
  } catch (error: any) {
    console.error('Miniapp auth-sync error:', error);
    res.status(500).json({ error: error.message });
  }
});

export default router;
