/**
 * Centralised Redis cache-key helpers.
 * Import from here instead of defining key functions inline.
 */

/** Short-lived one-time token generated by the Bot for Mini App auth (TTL: 10 min). */
export function tempTokenKey(token: string): string {
  return `bot_temp_token:${token}`;
}

/** Long-lived session token issued after successful exchange (TTL: 24 h). */
export function sessionTokenKey(token: string): string {
  return `session_token:${token}`;
}
