/**
 * Centralised Redis cache-key helpers.
 * Import from here instead of defining key functions inline.
 */

/** Short-lived one-time token generated by the Bot for Mini App auth (TTL: 10 min). */
export function tempTokenKey(token: string): string {
  return `bot_temp_token:${token}`;
}

/** Long-lived session token issued after successful exchange (TTL: 24 h). */
export function sessionTokenKey(token: string): string {
  return `session_token:${token}`;
}

/**
 * One-time token for Mini App auth via ?jt= URL parameter (TTL: 30 min).
 * Generated by the Bot on /start; consumed once by POST /api/miniapp/jt-auth.
 * This mechanism bypasses Telegram initData HMAC entirely, which fixes the
 * "initData empty" bug observed when Keyboard web_app buttons open the Mini App.
 */
export function jtTokenKey(token: string): string {
  return `miniapp_jt:${token}`;
}
