-- Migration 012: No-op placeholder.
-- Default deposit network seed data has been intentionally removed.
-- Networks are managed exclusively by admins through the admin panel.
-- This file is kept to preserve migration numbering order.
