-- Migration 101_landing_config: Seed landing page configuration into system_settings
-- All keys are public (is_public = true) so the landing API can read without auth

INSERT INTO system_settings (key, value, description, category, is_public) VALUES
('landing_brand_name',         '"ENKPay"', '官网品牌名称', 'landing', true),
('landing_logo_url',           '""', '品牌 Logo URL（/uploads/logos/xxx.png）', 'landing', true),
('landing_slogan_zh', '"链接每一个人的数字价值"', 'Slogan 中文', 'landing', true),
('landing_slogan_en', '"Connecting Everyone''s Digital Value"', 'Slogan 英文', 'landing', true),
('landing_slogan_fr', '"Connecter la valeur numérique de chacun"', 'Slogan 法语', 'landing', true),
('landing_slogan_de', '"Den digitalen Wert jedes Menschen verbinden"', 'Slogan 德语', 'landing', true),
('landing_slogan_es', '"Conectando el valor digital de todos"', 'Slogan 西语', 'landing', true),
('landing_slogan_ar', '"ربط القيمة الرقمية للجميع"', 'Slogan 阿语', 'landing', true),
('landing_slogan_ja', '"すべての人のデジタル価値をつなぐ"', 'Slogan 日语', 'landing', true),
('landing_social_facebook',  '""', 'Facebook 链接', 'landing', true),
('landing_social_tiktok',    '""', 'TikTok 链接', 'landing', true),
('landing_social_twitter',   '""', 'X/Twitter 链接', 'landing', true),
('landing_social_telegram',  '""', 'Telegram 频道链接', 'landing', true),
('landing_social_youtube',   '""', 'YouTube 链接', 'landing', true),
('landing_social_instagram', '""', 'Instagram 链接', 'landing', true),
('landing_contact_telegram', '""', '联系 Telegram 用户名（不含@）', 'landing', true),
('landing_privacy_zh', '""', '隐私政策 中文', 'landing', true),
('landing_privacy_en', '""', '隐私政策 英文', 'landing', true),
('landing_privacy_fr', '""', '隐私政策 法语', 'landing', true),
('landing_privacy_de', '""', '隐私政策 德语', 'landing', true),
('landing_privacy_es', '""', '隐私政策 西语', 'landing', true),
('landing_privacy_ar', '""', '隐私政策 阿语', 'landing', true),
('landing_privacy_ja', '""', '隐私政策 日语', 'landing', true),
('landing_terms_zh', '""', '服务条款 中文', 'landing', true),
('landing_terms_en', '""', '服务条款 英文', 'landing', true),
('landing_terms_fr', '""', '服务条款 法语', 'landing', true),
('landing_terms_de', '""', '服务条款 德语', 'landing', true),
('landing_terms_es', '""', '服务条款 西语', 'landing', true),
('landing_terms_ar', '""', '服务条款 阿语', 'landing', true),
('landing_terms_ja', '""', '服务条款 日语', 'landing', true),
('landing_stat_users_override',   '0',  '用户数手动覆盖（0=自动）', 'landing', true),
('landing_stat_nft_override',     '0',  'NFT数手动覆盖（0=自动）', 'landing', true),
('landing_stat_charity_override', '0',  '公益额手动覆盖（0=自动）', 'landing', true),
('landing_stat_countries',        '30', '覆盖国家数量', 'landing', true),
('landing_enabled', 'true', '官网是否启用', 'landing', true)
ON CONFLICT (key) DO NOTHING;
